version: "2.0"
services:
  test1:
    container_name: Integration_test1
    build: .
    image: postman_report
    command:
      - run Fruits.postman_collection.json
      - --environment QA.postman_environment.json
      - -r html,cli
      - --reporter-html-export report/report.html
      - --reporter-html-template report/template.hbs
    volumes:
      - ./src:/etc/newman
