name: docker-compose-actions-workflow
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 12 * * 5'
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.3
      
      - name: Step 1 - Run Docker 1
        run: docker-compose up
        
      - name: Step 2 - Run Docker 2
        run: docker-compose -f docker-compose.yml -f docker-compose.qa.yml up -d
        
      - name: Step 3 - Attach Report
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Report
          path: src/report/report.html
